name: mask2face
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7,<3.9
  - pip==20.2.3
  - notebook==6.1.4
  - tensorflow==2.2.0  # for MAC use lower version
  - tensorflow-gpu==2.2.0  # comment for systems without GPU
  - numpy==1.19.1
  - ipywidgets==7.5.1
  - pandas==1.1.3
  - matplotlib==3.3.2
  - seaborn==0.11.0
  - Pillow==7.2.0
  - imutils==0.5.3
  - mtcnn==0.1.0
  - scikit-learn==0.23.2
  - dlib==19.21.1
  - tqdm==4.59.0
  - requests==2.25.1
  - pip:
      - -r file:requirements.txt
